### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by pontikis** [yrfandrew/editorjs2-subscript#1]
Hello! Thanks for this software.

I use editor.js 2.19.1 and I am trying to add your Tool

```
                tools: {
                    header: {
                        class: Header,
                        inlineToolbar: true,
                    },
                    list: {
                        class: List,
                        inlineToolbar: true,
                    },
                    Marker: {
                        class: Marker,
                        shortcut: "CMD+SHIFT+M",
                    },
                    underline: {
                        class: Underline,
                        shortcut: "CMD+U",
                    },
                    subscript: {
                        class: Subscript
                    },
                },
```

However I get the error "Uncaught (in promise) TypeError: Cannot read property 'status' of undefined"

Without "subscript" everything works fine.

(the same with superscript tool)

Any ideas?

**Comment by pontikis** [comment]
Hello again

I suppose the `require` statement 
```
    get toolboxIcon() {
        return require('./assets/subscript.svg').default;
    }
```

causes the error (I work in **browser** mode in current project)

A work around (in my case) is this method to return the innerHTML directly

Thanks again!

**Comment by yrfandrew** [comment]
> Hello again
> 
> I suppose the `require` statement
> 
> ```
>     get toolboxIcon() {
>         return require('./assets/subscript.svg').default;
>     }
> ```
> 
> causes the error (I work in **browser** mode in current project)
> 
> A work around (in my case) is this method to return the innerHTML directly
> 
> Thanks again!

----
Hello Pontikis:

I used the simplest code, but I can't reproduce the problem you asked.

I used Vue 3.0.x to build.


```
// public/index.html

<body>
  <div id="app"></div>
  <script type="module" src="/src/main.js"></script>
</body>
```

```
// component/Editor.vue

<template>
  <div id="docEditor"></div>
</template>

<script>
import { onMounted } from "vue"
import EditorJS from "@editorjs/editorjs"
import Subscript from "editorjs2-subscript"
export default {
  name: "App",
  setup () {
    onMounted(() => {
      new EditorJS({
        data: {
          condition: {},
          blocks: []
        },
        holder: "docEditor",
        tools: {
          subscript: {
            class: Subscript
          }
        }
      })
    })
  }
};
</script>
```
Hope this reply can give you a reference.

**Comment by pontikis** [comment]
Hello @yrfandrew 

thank you for your reply.

Yes, of course, it will work with Vue (or any framework with Node.js)

But for those use the old **browser mode** will not work as `require ` statement produces the error.

A common workaround is to use HTML for SVG files.

For example:

subscript.svg
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16"><path fill="none" d="M0 0h24v24H0z"/><path d="M5.596 4L10.5 9.928 15.404 4H18l-6.202 7.497L18 18.994V19h-2.59l-4.91-5.934L5.59 19H3v-.006l6.202-7.497L3 4h2.596zM21.55 16.58a.8.8 0 1 0-1.32-.36l-1.155.33A2.001 2.001 0 0 1 21 14a2 2 0 0 1 1.373 3.454L20.744 19H23v1h-4v-1l2.55-2.42z"/></svg>
```
superscript.svg
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="16" height="16"><path fill="none" d="M0 0h24v24H0z"/><path d="M5.596 5l4.904 5.928L15.404 5H18l-6.202 7.497L18 19.994V20h-2.59l-4.91-5.934L5.59 20H3v-.006l6.202-7.497L3 5h2.596zM21.55 6.58a.8.8 0 1 0-1.32-.36l-1.155.33A2.001 2.001 0 0 1 21 4a2 2 0 0 1 1.373 3.454L20.744 9H23v1h-4V9l2.55-2.42z"/></svg>
```

Thanks again!
